### ISSUE TITLE
New icon: adding Jetpack icon in Gridicons

### ISSUE THREAD

**Issue by AnnaMag** [Automattic/gridicons#261] opened 2017-11-14 10:15 UTC
While working on issues in Calypso I found that having an JP icon as part of the Gridicons set would help keep the layout standardized, e.g. https://github.com/Automattic/wp-calypso/issues/18893 would not be happening. 

Is adding a Jetpack icon to Gridicons a possibility?

**Comment by folletto** [comment] 2017-11-14 10:20
The current approach is that any logo should not be in Gridicons. 

We have Social Logos: https://github.com/Automattic/social-logos

Social logos should build in a similar way to Gridicons (even if, I still have to port the updated build process), but it's more careful to make sure that the correct logos are used.

I won't close this issue right off just to see if we might want to review this decision.

**Comment by AnnaMag** [comment] 2017-11-14 10:26
Thanks @folletto for putting it in a context. It makes sense code-wise and wanted to check-in about the design perspective.

**Comment by drw158** [comment] 2017-11-14 15:33
I believe this is a dupe of #240 

I made that issue a while ago, but I think my reasoning was:

It's a similar situation to the My Sites icon. The Jetpack logo has become an icon. We may need to tweak the Jetpack logo, and the Social Logo icons are not tweaked at all; the vectors are untouched.

**Comment by folletto** [comment] 2017-11-14 15:46
If we introduce it as "Plans" icon with tweaked proportions, it would fit the need, you're right. I would avoid to include it as a "Jetpack" icon tho, similar to "My Sites" is not "WordPress".

**Comment by mattmiklic** [comment] 2018-01-10 18:42
The Jetpack logo is now being used as the icons for the Plans link in Calypso nav. @MichaelArestad created a 24px version of the logo that should align with Gridicons in https://github.com/Automattic/wp-calypso/pull/20718.

**Comment by mattmiklic** [comment] 2018-01-10 21:04
Resolved by #273.

**Closed by mattmiklic** 2018-01-10 21:04 UTC
Labels: icon request, question
